// AUTO-GENERATED by scripts/extract.py — lists every paper JSON.
// You can also edit by hand: add an import and include it in `papersData`.

import AustinIci from "./papers/austin-ici.json";
import CindexSupplementary from "./papers/cindex-supplementary.json";
import CompetingRisksPrognostic from "./papers/competing-risks-prognostic.json";
import ConcordanceCompetingRisks from "./papers/concordance-competing-risks.json";
import ConcordanceVignette from "./papers/concordance-vignette.json";
import DesctoolsPackage from "./papers/desctools-package.json";
import IbsSurvivalMetrics from "./papers/ibs-survival-metrics.json";
import InternalValidation from "./papers/internal-validation.json";
import PecPackage from "./papers/pec-package.json";
import RiskregressionPackage from "./papers/riskregression-package.json";
import RmsPackage from "./papers/rms-package.json";
import SurvivalPackage from "./papers/survival-package.json";

export const papersData = [AustinIci, CindexSupplementary, CompetingRisksPrognostic, ConcordanceCompetingRisks, ConcordanceVignette, DesctoolsPackage, IbsSurvivalMetrics, InternalValidation, PecPackage, RiskregressionPackage, RmsPackage, SurvivalPackage];
