// AUTO-GENERATED by scripts/extract.py — lists every paper JSON.
// You can also edit by hand: add an import and include it in `papersData`.
import austinIci from "./papers/austin-ici.json";

export const papersData = [austinIci];
